#### 배열 만들기

ndarray는 내부 모든 자료형이 같아야 함. 

In [1]:
# 리스트에서 배열 만들기
import numpy as np
a = np.array([1, 4, 2, 5, 3])
b = np.array([3.14, 4, 2, 3])
c = np.array([1, 2, 3, 4], dtype = float)
print(a, b, c)

[1 4 2 5 3] [3.14 4.   2.   3.  ] [1. 2. 3. 4.]


In [2]:
a

array([1, 4, 2, 5, 3])

In [3]:
b

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
c

array([1., 2., 3., 4.])

In [2]:
# 함수를 이용하여 배열 만들기
a = np.zeros(10, dtype = int) # 0으로 채운 배열 생성
b = np.ones((3, 5), dtype = float) #1로 채운 배열 생성
c = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기 
d = np.arange(0, 20, 2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성
e = np.linspace(0, 1, 5) # 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
f = np.random.random((3,3)) # 3*3 크기의 난수 배열 생성
g = np.random.normal(0, 1, (3, 3)) # 평균 0, 표준 편차 1의 정규 분포를 따르는 3*3 난수 배열
h = np.random.randint(0, 10, (3, 3)) # [0, 10) 구간의 임의로 정수로 채운 3*3 배열 만들기
i = np.eye(3) # 크기 3의 단위 행렬 만들기

print("np.zeros(10, dtype = int):\n", a)
print("\nnp.ones((3, 5), dtype = float):\n", b)
print("\nnp.full((3,5), 3.14):\n", c)
print("\nnp.arange(0, 20, 2):\n", d)
print("\nnp.linspace(0, 1, 5):\n", e)
print("\nnp.random.random((3,3)):\n", f)
print("\nnp.random.normal(0, 1, (3, 3)):\n", g)
print("\nnp.random.randint(0, 10, (3, 3)):\n", h)
print("\nnp.eye(3):\n", i)

np.zeros(10, dtype = int):
 [0 0 0 0 0 0 0 0 0 0]

np.ones((3, 5), dtype = float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

np.full((3,5), 3.14):
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

np.arange(0, 20, 2):
 [ 0  2  4  6  8 10 12 14 16 18]

np.linspace(0, 1, 5):
 [0.   0.25 0.5  0.75 1.  ]

np.random.random((3,3)):
 [[0.18262827 0.27692481 0.69023281]
 [0.55079247 0.28145341 0.07734313]
 [0.63129821 0.39951056 0.36086524]]

np.random.normal(0, 1, (3, 3)):
 [[ 2.00213728 -0.22744782  0.07246514]
 [-1.49533855  0.2893585   0.35447377]
 [ 0.52527444 -1.6999584  -0.22105502]]

np.random.randint(0, 10, (3, 3)):
 [[4 1 8]
 [5 3 1]
 [0 1 9]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 인덱싱과 슬라이싱

In [5]:
# 기본적인 인덱싱과 슬라이싱
x1 = np.array([1, 3, 5, 7, 9])

print("x1[0]:", x1[0]) # 양수 인덱스 (맨 앞 요소)
print("x1[3]:", x1[3]) # 세 번째 요소 
print("x1[-1]:", x1[-1]) # 음수 인덱스 (맨 뒤 요소)
print("x1[-2]:", x1[-2]) # 뒤에서 네 번째 요소 

print("x1[1:3]:", x1[1:3]) # 1번째 요소부터 3번째 요소까지 슬라이싱

x1[0]: 1
x1[3]: 7
x1[-1]: 9
x1[-2]: 7
x1[1:3]: [3 5]


In [8]:
x2

array([[0.95993715, 0.89384616, 0.86637042, 0.74422476, 0.2076551 ],
       [0.90450119, 0.09896062, 0.5980032 , 0.72525142, 0.37142647],
       [0.82978847, 0.40735121, 0.02646538, 0.64321665, 0.6424685 ],
       [0.15657183, 0.89127111, 0.9024431 , 0.82924352, 0.50654717],
       [0.91795215, 0.34967258, 0.44742199, 0.69074884, 0.54005106],
       [0.57210752, 0.46614885, 0.94497135, 0.03666224, 0.15319774],
       [0.44669552, 0.96712778, 0.33405666, 0.87628173, 0.59547695],
       [0.9266934 , 0.67006163, 0.06378979, 0.79796435, 0.92641776],
       [0.07485477, 0.14514047, 0.37148092, 0.36692883, 0.98838882],
       [0.88598766, 0.14705731, 0.15832775, 0.20842547, 0.0775289 ]])

2차원 배열의 경우

In [6]:
# 2차원 배열의 인덱싱 및 슬라이싱
x2 = np.random.random(size = (10, 5))

print("x2[0, 1]", x2[0, 1])
print("x2[1:4, 2]\n", x2[1:4, 2])
print("x2[0, 2:4]\n", x2[0, 2:4])
print("x2[0:3, 2:4]\n", x2[0:3, 2:4])

x2[0, 1] 0.8855504039536837
x2[1:4, 2]
 [0.09397457 0.56412707 0.49113127]
x2[0, 2:4]
 [0.99694676 0.51587565]
x2[0:3, 2:4]
 [[0.99694676 0.51587565]
 [0.09397457 0.01775805]
 [0.56412707 0.93719231]]


In [7]:
x2

array([[0.51417385, 0.8855504 , 0.99694676, 0.51587565, 0.19817207],
       [0.7143646 , 0.46613338, 0.09397457, 0.01775805, 0.87675945],
       [0.24718937, 0.07283701, 0.56412707, 0.93719231, 0.60831518],
       [0.62372684, 0.32507082, 0.49113127, 0.79532232, 0.66100076],
       [0.5146838 , 0.01532614, 0.42684054, 0.20992595, 0.39574485],
       [0.25466564, 0.11276444, 0.91494391, 0.66103976, 0.99502847],
       [0.13028542, 0.23115483, 0.04976894, 0.03884503, 0.09163161],
       [0.4388513 , 0.58283797, 0.40252042, 0.41742207, 0.20675863],
       [0.68688807, 0.6148141 , 0.39462684, 0.75821128, 0.20419749],
       [0.43792159, 0.34635797, 0.57973658, 0.39126604, 0.93333318]])

#### 유니버설 함수

- 배열 간 이항 연산(대응되는 요소끼리)을 지원

In [21]:
# 사용 기초
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])

print("x + y = ", x + y)
print("x - y = ", x - y)
print("x * y = ", x * y)
print("x / y = ", x / y)
print("log x = ", np.log(x))

x + y =  [5 5 5 5]
x - y =  [-3 -1  1  3]
x * y =  [4 6 6 4]
x / y =  [0.25       0.66666667 1.5        4.        ]
log x =  [0.         0.69314718 1.09861229 1.38629436]


In [8]:
# 루프와 유니버설 함수의 속도 비교
arr_1 = np.random.randint(1, 10, size = 10 ** 8)
arr_2 = np.random.randint(1, 10, size = 10 ** 8)
import time
### 리스트를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = []
for val1, val2 in zip(arr_1, arr_2):
    output.append(val1 + val2)
t2 = time.time()
print("반복문을 사용한 경우:", round(t2 - t1, 4))

### 유니버설 함수를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = arr_1 + arr_2
t2 = time.time()
print("유니버설 함수를 사용한 경우:", round(t2 - t1, 4))

반복문을 사용한 경우: 43.4976
유니버설 함수를 사용한 경우: 11.7772


##### Broadcasting
- 서로 다른 dimension을 더하거나 곱할 때, 자동으로 크기를 맞춰주게 된다. 

In [11]:
# 브로드캐스팅
print("np.arange(3) + 5:", 
      np.arange(3) + 5, '\n')

print("np.ones((3, 3)) + np.arange(3)\n",
      np.ones((3, 3)) + np.arange(3), '\n')

print("np.arange(3).reshape(3, 1) + np.arange(3)\n",
      np.arange(3).reshape(3, 1) + np.arange(3))

np.arange(3) + 5: [5 6 7] 

np.ones((3, 3)) + np.arange(3)
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

np.arange(3).reshape(3, 1) + np.arange(3)
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [11]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [12]:
np.arange(3)

array([0, 1, 2])

In [15]:
X, Xmean, Xstd

(array([[0.52437062, 0.0759482 , 0.50066266],
        [0.74749053, 0.35280138, 0.68677287],
        [0.43782544, 0.81798891, 0.73205706],
        [0.61885066, 0.68476178, 0.30275527],
        [0.96595183, 0.23111972, 0.86265464],
        [0.81007147, 0.47939233, 0.48031116],
        [0.85936317, 0.90875357, 0.66725766],
        [0.57097249, 0.17859196, 0.8673559 ],
        [0.90021587, 0.74039733, 0.92245405],
        [0.30018004, 0.08395466, 0.81753292]]),
 array([0.67352921, 0.45537098, 0.68398142]),
 array([0.20645773, 0.29846478, 0.19059774]))

In [13]:
# 브로드캐스팅 예시: z - normalization
X = np.random.random((10, 3))
Xmean = X.mean(axis = 0) # 열별 평균 크기: (1, 3)
Xstd = X.std(axis = 0) # 열별 표준편차 크기: (1, 3)

Z = (X - Xmean) / Xstd

print("X:", X)
print("\nXmean:\n", Xmean)
print("\nXstd:\n", Xstd)
print("\nZ:\n", Z)

X: [[0.52437062 0.0759482  0.50066266]
 [0.74749053 0.35280138 0.68677287]
 [0.43782544 0.81798891 0.73205706]
 [0.61885066 0.68476178 0.30275527]
 [0.96595183 0.23111972 0.86265464]
 [0.81007147 0.47939233 0.48031116]
 [0.85936317 0.90875357 0.66725766]
 [0.57097249 0.17859196 0.8673559 ]
 [0.90021587 0.74039733 0.92245405]
 [0.30018004 0.08395466 0.81753292]]

Xmean:
 [0.67352921 0.45537098 0.68398142]

Xstd:
 [0.20645773 0.29846478 0.19059774]

Z:
 [[-0.72246553 -1.27124812 -0.96180971]
 [ 0.35823952 -0.34365732  0.01464578]
 [-1.14165631  1.21494379  0.25223616]
 [-0.2648414   0.76856908 -2.00016093]
 [ 1.4163801  -0.75134917  0.93743618]
 [ 0.66135697  0.08048301 -1.06858697]
 [ 0.90010656  1.51904889 -0.08774372]
 [-0.4967444  -0.92734233  0.96210208]
 [ 1.09798099  0.95497482  1.2511829 ]
 [-1.80835649 -1.24442264  0.70069824]]


#### 비교 연산자

- 여기도 똑같이 내부적으로 broadcasting이 되어가고 있는 것. 

In [16]:
L = np.array([1, 2, 3, 4, 5])
L >= 3

array([False, False,  True,  True,  True])

In [17]:
# 비교 연산자
L = np.array([1, 2, 3, 4, 5])
cond = L >= 3
sum(cond) # 조건을 만족하는 요소의 개수

3

In [18]:
L[cond] # 조건을 만족하는 요소만 반환

array([3, 4, 5])